"""Generated by gen_shims.py from a Linux host's 'fcntl' module. Do not edit.

Pyodide has no fcntl. Nothing on labgrid's QEMU/console path actually needs a
tty, so the constants are what matter: they exist so that dependent modules
import and so that `from termios import *` style code finds its names.
Operations that genuinely require a terminal raise OSError(ENOTTY) rather than
silently pretending to succeed.
"""
import errno as _errno


DN_ACCESS = 1
DN_ATTRIB = 32
DN_CREATE = 4
DN_DELETE = 8
DN_MODIFY = 2
DN_MULTISHOT = 2147483648
DN_RENAME = 16
FASYNC = 8192
FD_CLOEXEC = 1
F_ADD_SEALS = 1033
F_DUPFD = 0
F_DUPFD_CLOEXEC = 1030
F_EXLCK = 4
F_GETFD = 1
F_GETFL = 3
F_GETLEASE = 1025
F_GETLK = 5
F_GETLK64 = 5
F_GETOWN = 9
F_GETPIPE_SZ = 1032
F_GETSIG = 11
F_GET_SEALS = 1034
F_NOTIFY = 1026
F_OFD_GETLK = 36
F_OFD_SETLK = 37
F_OFD_SETLKW = 38
F_RDLCK = 0
F_SEAL_GROW = 4
F_SEAL_SEAL = 1
F_SEAL_SHRINK = 2
F_SEAL_WRITE = 8
F_SETFD = 2
F_SETFL = 4
F_SETLEASE = 1024
F_SETLK = 6
F_SETLK64 = 6
F_SETLKW = 7
F_SETLKW64 = 7
F_SETOWN = 8
F_SETPIPE_SZ = 1031
F_SETSIG = 10
F_SHLCK = 8
F_UNLCK = 2
F_WRLCK = 1
LOCK_EX = 2
LOCK_MAND = 32
LOCK_NB = 4
LOCK_READ = 64
LOCK_RW = 192
LOCK_SH = 1
LOCK_UN = 8
LOCK_WRITE = 128


def fcntl(fd, cmd, arg=0):
    """F_GETFL/F_SETFL are used to set O_NONBLOCK; harmless to no-op here."""
    return 0


def ioctl(fd, request, arg=0, mutate_flag=True):
    raise OSError(_errno.ENOTTY, "ioctl is not available in the browser")


def flock(fd, operation):
    return None


def lockf(fd, cmd, len=0, start=0, whence=0):
    return None
