"""Generated by gen_shims.py from a Linux host's 'resource' module. Do not edit.

Pyodide has no resource. Nothing on labgrid's QEMU/console path actually needs a
tty, so the constants are what matter: they exist so that dependent modules
import and so that `from termios import *` style code finds its names.
Operations that genuinely require a terminal raise OSError(ENOTTY) rather than
silently pretending to succeed.
"""
import errno as _errno


RLIMIT_AS = 9
RLIMIT_CORE = 4
RLIMIT_CPU = 0
RLIMIT_DATA = 2
RLIMIT_FSIZE = 1
RLIMIT_MEMLOCK = 8
RLIMIT_MSGQUEUE = 12
RLIMIT_NICE = 13
RLIMIT_NOFILE = 7
RLIMIT_NPROC = 6
RLIMIT_OFILE = 7
RLIMIT_RSS = 5
RLIMIT_RTPRIO = 14
RLIMIT_RTTIME = 15
RLIMIT_SIGPENDING = 11
RLIMIT_STACK = 3
RLIM_INFINITY = -1
RUSAGE_CHILDREN = -1
RUSAGE_SELF = 0
RUSAGE_THREAD = 1

RLIM_INFINITY = -1


def getrlimit(resource_):
    return (1024, 4096)


def setrlimit(resource_, limits):
    return None


def getrusage(who):
    raise OSError(_errno.ENOSYS, "getrusage is not available in the browser")


def getpagesize():
    return 65536
