#!/usr/bin/env python3
"""Generate the stdlib shims from a real Linux host.

Pyodide cannot import termios, fcntl or resource. Everything labgrid needs on
top of them -- pty, tty, pexpect, ptyprocess, pyserial -- imports unmodified
once those three exist, so these three files are the entire compatibility
layer for the Python standard library.

They are generated rather than hand-written so they are complete by
construction: every constant the real module exports is present, instead of
being discovered one AttributeError at a time. setup.sh runs this on the host
(Linux required) on every run; the output is generated, so it lands in the
untracked build tree rather than next to this script.

Usage: gen_shims.py [output-dir]
"""
import os
import sys

HEADER = '''\
"""Generated by gen_shims.py from a Linux host's {mod!r} module. Do not edit.

Pyodide has no {mod}. Nothing on labgrid's QEMU/console path actually needs a
tty, so the constants are what matter: they exist so that dependent modules
import and so that `from termios import *` style code finds its names.
Operations that genuinely require a terminal raise OSError(ENOTTY) rather than
silently pretending to succeed.
"""
import errno as _errno

'''


def constants(mod):
    out = []
    for name in sorted(dir(mod)):
        if name.startswith("_"):
            continue
        val = getattr(mod, name)
        if isinstance(val, int):
            out.append(f"{name} = {val}")
    return out


def gen_termios():
    import termios

    body = [HEADER.format(mod="termios")]
    body.append("\n".join(constants(termios)))
    body.append('''

class error(OSError):
    """termios.error"""


def _default_attrs():
    cc = [b"\\x00"] * NCCS
    cc[VINTR] = b"\\x03"
    cc[VQUIT] = b"\\x1c"
    cc[VERASE] = b"\\x7f"
    cc[VKILL] = b"\\x15"
    cc[VEOF] = b"\\x04"
    cc[VMIN] = 1
    cc[VTIME] = 0
    # a plausible 8N1 raw-ish line, which is what QEMU's console looks like
    return [IGNPAR, 0, B115200 | CS8 | CREAD | CLOCAL, 0, B115200, B115200, cc]


def tcgetattr(fd):
    return _default_attrs()


def tcsetattr(fd, when, attributes):
    return None


def tcsendbreak(fd, duration):
    return None


def tcdrain(fd):
    return None


def tcflush(fd, queue):
    return None


def tcflow(fd, action):
    return None


def tcgetwinsize(fd):
    return (24, 80)


def tcsetwinsize(fd, winsize):
    return None
''')
    return "\n".join(body)


def gen_fcntl():
    import fcntl

    body = [HEADER.format(mod="fcntl")]
    body.append("\n".join(constants(fcntl)))
    body.append('''

def fcntl(fd, cmd, arg=0):
    """F_GETFL/F_SETFL are used to set O_NONBLOCK; harmless to no-op here."""
    return 0


def ioctl(fd, request, arg=0, mutate_flag=True):
    raise OSError(_errno.ENOTTY, "ioctl is not available in the browser")


def flock(fd, operation):
    return None


def lockf(fd, cmd, len=0, start=0, whence=0):
    return None
''')
    return "\n".join(body)


def gen_resource():
    import resource

    body = [HEADER.format(mod="resource")]
    body.append("\n".join(constants(resource)))
    body.append('''
RLIM_INFINITY = -1


def getrlimit(resource_):
    return (1024, 4096)


def setrlimit(resource_, limits):
    return None


def getrusage(who):
    raise OSError(_errno.ENOSYS, "getrusage is not available in the browser")


def getpagesize():
    return 65536
''')
    return "\n".join(body)


def main():
    if not sys.platform.startswith("linux"):
        sys.exit("run this on Linux: the point is to copy a real libc's constants")
    out = sys.argv[1] if len(sys.argv) > 1 else "build/shims"
    os.makedirs(out, exist_ok=True)
    for name, gen in (("termios", gen_termios), ("fcntl", gen_fcntl), ("resource", gen_resource)):
        path = os.path.join(out, name + ".py")
        with open(path, "w") as fh:
            fh.write(gen())
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
