name: unit tests

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: |
        sudo apt install -yq python3-pip
        python3 -m pip install --upgrade pip setuptools wheel
    - name: Build docker images
      run: |
        ./dockerfiles/build.sh
        cd dockerfiles/staging
        docker-compose up --exit-code-from client client || (docker-compose logs --timestamps && false)
        docker-compose down
    - name: Show docker images
      run: |
        docker images
